---
title: "skittles"
output: html_document
---

# --- settings ---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# --- analysis ---

```{r}
skittles <-
tibble::tribble(~purple, ~red, ~orange, ~yellow, ~green,
                11, 16, 10, 10, 10,
                8, 11, 17, 12, 9,
                6, 7, 13, 15, 17,
                10, 10, 9, 16, 13,
                10, 13, 10, 10, 14,
                11, 11, 15, 10, 10)
skittles
```

```{r}
(flavors_empirical <- colSums(skittles))
```

```{r}
chisq.test(rbind(flavors_empirical, # observed
                 rep(sum(flavors_empirical)/5, 5))) # expected (if equal props)

```

# --- analysis ---

redo twitter analysis

```{r}
chisq.test(skittles)
```
check that chi-square would not be sig, if props differ within row, but same across rows

```{r}
check <-
  tibble::tribble(~yes, ~no, ~maybe,
                  70, 20, 10,
                  70, 20, 10,
                  70, 20, 10)
check
```

```{r}
chisq.test(check)
```